import = [".config/alacritty.local.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 75

[env]
TERM = "xterm-256color"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
opacity = 0.95
